Update the bundled Windows version of the Transifex client to a newer version from here (https://github.com/Swyter/sphinx-l10n/blob/master/tx.exe). Fixing the various spurious errors:
    Converting format...
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xf3 in position 233: invalid continuation byte
    Reverting format...

...and...

    MaxRetryError: HTTPSConnectionPool(host='www.transifex.com', port=None): Max retries exceeded with url: https://www.transifex.com/api/2/project/tld/resource/dialogs/stats/ (Caused by <class 'socket.error'>: [Errno 10054]